name: Arch Linux Package

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-archlinux:
    name: Package (Arch Linux)
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm go git

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build package
        run: |
          useradd -m build
          chown -R build:build .
          su - build -c "cd $GITHUB_WORKSPACE/contrib/archlinux && PKGDEST=$GITHUB_WORKSPACE/arch-artifacts makepkg -f --noconfirm --nodeps"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Arch Linux package
          path: arch-artifacts/*.pkg.tar.zst
          if-no-files-found: error
